---
title: "Proyecto"
output: html_notebook
Nombre_Estudiantes: "Marlon Estuardo Rodríguez Vásquez, Carlos Augusto Monterroso Lima"
---


#Inclusion de librerias
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
```


#Carga de archivos
```{r}
proyectoInovacion = read_csv('proyectos_innovacion.csv')
paisesPib = read_csv('paises_pib.csv')

head(proyectoInovacion)
str(proyectoInovacion)

head(paisesPib)
str(paisesPib)
```
#Parte II
#Creación de listas.
```{r}

# Lista de países
listaPaises <- proyectoInovacion %>%
  group_by(pais) %>%
  summarize()
# Lista de áreas tecnológicas
listaAreas <- proyectoInovacion %>%
  group_by(area_tecnologica) %>%
  summarize()

#se raeliza el calculo para las estadisticas iniciales
proyectosTotales = sum(proyectoInovacion$presupuesto_usd > 0)
presupuestoPromedio = mean(proyectoInovacion$presupuesto_usd)
promedioPublicaciones = mean(proyectoInovacion$publicaciones)
promedioInvestigadores = mean(proyectoInovacion$investigadores)

estadisticasIniciales <- data_frame (
    proyectosTotales,
    presupuestoPromedio,
    promedioPublicaciones,
    promedioInvestigadores
  )


# Subconjuntos de proyectos por área tecnológica
proyectosPorArea <- lapply(listaAreas$area_tecnologica, function(area) {
  proyectoInovacion %>%
    filter(area_tecnologica == area)
  }
)

listaProyecto <- list( dataframeOriginal = proyectoInovacion, paises = listaPaises,
  areasTecnologicas = listaAreas, estadisticas = estadisticasIniciales,
  proyectosPorArea = proyectosPorArea
)

listaProyecto

#uso de lapply
promediosAreaTecno <- lapply(proyectosPorArea, function(df) {
  list(
    area = df$area_tecnologica[1],
    presupuestoPromedio = mean(df$presupuesto_usd),
    promedioPublicaciones = mean(df$publicaciones),
    promedioInvestigadores = mean(df$investigadores)
  )
})

listaIndicadores <- lapply(proyectosPorArea, function(df) {
  list(
    area = df$area_tecnologica[1],
    proyectos = nrow(df),
    presupuestoPromedio = mean(df$presupuesto_usd),
    promedioPublicaciones = mean(df$publicaciones),
    productividadPromedio = mean(df$publicaciones / df$investigadores)
  )
})

promediosAreaTecno
listaIndicadores

```

#Parte III
```{r}
#nuevas variables utilizando mutate
proyectoInovacion <- proyectoInovacion %>%
  mutate(
    productividad = publicaciones / investigadores,
    intensidad_investigacion = investigadores / duracion_meses,
    indice_resultados = (publicaciones + 2 * patentes) / presupuesto_usd
  )

# Presupuesto promedio por país y área tecnológica
presupuesto_pais_area <- proyectoInovacion %>%
  group_by(pais, area_tecnologica) %>%
  summarize(presupuesto_promedio = mean(presupuesto_usd))

presupuesto_pais_area 

# Número de proyectos por año
# evaluamos presupuesto mayor a 0, en el csv actualmente todos tienen presupuesto 
#pero pusimos esto como una validacion por si hubieran valores 0
proyectos_por_anio <- proyectoInovacion %>%
  group_by(anio_inicio) %>%
  summarize(proyectos_totales= sum(presupuesto_usd > 0))

proyectos_por_anio
  
# Productividad promedio por área tecnológica y nivel de impacto
productividad_area_impacto <- proyectoInovacion %>%
  group_by(area_tecnologica, impacto) %>%
  summarize(productividad_promedio = mean(productividad))

productividad_area_impacto 

# generar rankings utilizando arrange(desc(variable))

# Top 10 proyectos con mayor eficiencia
top_10_eficiencia <- proyectoInovacion %>%
  arrange(desc(indice_resultados)) %>%
  head(10)

# Top 5 países con mayor productividad promedio
top_5_paises_productividad <- proyectoInovacion %>%
  group_by(pais) %>%
  summarize(prod_promedio_pais = mean(productividad)) %>%
  arrange(desc(prod_promedio_pais)) %>%
  head(5)

#visualizacion 10 proyectos con mayor eficiencia
top_10_eficiencia

#visualización 5 paises con mayor productividad promedio
top_5_paises_productividad


listaProyecto$dataframeOriginal <- proyectoInovacion

```
#Parte IV
```{r}
#se realiza el calculo de los indicadores por pais
indicadoresPorPais <- proyectoInovacion %>%
  group_by(pais) %>%
  summarize(
    numeroProyectos = length(presupuesto_usd),
    presupuesto_promedio = mean(presupuesto_usd)
  )

indicadoresPorPais

##Integrar los datasets
datosIntegrados <- indicadoresPorPais %>% 
  inner_join(paisesPib, by = "pais")
datosIntegrados

#indicadores proyecto por millon pib y presupuesto relativo
datosIntegrados <- datosIntegrados %>%
  mutate(
    proyectos_por_millon_pib = numeroProyectos / pib_millones,
    presupuesto_relativo = presupuesto_promedio / pib_millones
  )

paisesMayorInversion <- datosIntegrados %>%
  arrange(desc(presupuesto_relativo))

paisesMenorEficiencia <- datosIntegrados %>%
  arrange(desc(proyectos_por_millon_pib))

head(paisesMayorInversion)
head(paisesMenorEficiencia)

```

#Parte V
```{r}
# Funcion que evalua impacto - presupuesto - productividad
clasificar_proyecto <- function(impacto, presupuesto, productividad) {
  
  # Regla 1: Alto impacto y alta productividad
  if (impacto == "Alto" && productividad >= 1.5) {
    return("Proyecto estratégico")
    
  # Regla 2: Alto presupuesto y baja productividad
  } else if (presupuesto > 1000000 && productividad < 0.75) {
    return("Riesgo de ineficiencia")
    
  # Regla 3: Productividad media (entre 0.75 y 1.5)
  } else if (productividad >= 0.75 && productividad < 1.5) {
    return("Proyecto estándar")
    
  # Regla 4: Resto
  } else {
    return("Proyecto emergente")
  }
}

# Se aplica mapply dentro de mutate
proyectoInovacion <- proyectoInovacion %>%
  mutate(
    categoria_proyecto = mapply(
      clasificar_proyecto, 
      impacto, 
      presupuesto_usd, 
      productividad
    )
  )


# Se muestra el resultado de la nueva clasificación
proyectoInovacion %>% 
  select(pais, area_tecnologica, impacto, presupuesto_usd, productividad, categoria_proyecto) %>% 
  head(10)

```
##Parte VI
```{r}

lista_paises <- listaPaises$pais

indicadoresPorPaisFor <- data.frame(
  paisDf = character(),
  numeroProyectosDf = integer(),
  presupuestoTotalDf = numeric(),
  promedioPublicacionesDf = numeric(),
  eficienciaPromedioDf = numeric()
)

for (pais in lista_paises) {
  
  # Subconjunto por país
  dfPais <- proyectoInovacion %>%
    filter(pais == pais)
  
  # Cálculo de indicadores
  numeroProyectos <- nrow(dfPais)
  
  presupuestoTotal <- sum(dfPais$presupuesto_usd)
  
  promedioPublicaciones <- mean(dfPais$publicaciones)
  
  eficienciaPromedio <- mean(dfPais$indice_resultados)
  
  # Agregar fila al dataframe
  indicadoresPorPaisFor <- rbind(
    indicadoresPorPaisFor,
    data.frame(
      paisDf = pais,
      numeroProyectosDf = numeroProyectos,
      presupuestoTotalDf = presupuestoTotal,
      promedioPublicacionesDf = promedioPublicaciones,
      eficienciaPromedioDf = eficienciaPromedio
    )
  )
}

```
#Parte VI - while
```{r}
#vamos a revisar proyectos sobresalientes
media_eficiencia <- mean(proyectoInovacion$indice_resultados)
desv_eficiencia <- sd(proyectoInovacion$indice_resultados)
umbral_sobresaliente <- media_eficiencia + (2 * desv_eficiencia)

#Inicializar variables para el ciclo WHILE
proyectos_sobresalientes <- c() 
i <- 1                          
n <- nrow(proyectoInovacion)    

while (i <= n) {
  
  # Extrae la eficiencia del proyecto actual
  eficiencia_actual <- proyectoInovacion$indice_resultados[i]
  
  # Valida si supera el umbral
  if (!is.na(eficiencia_actual) && eficiencia_actual > umbral_sobresaliente) {
    # Almacena el identificador 
    proyectos_sobresalientes <- c(proyectos_sobresalientes, proyectoInovacion$id_proyecto[i])
  }
  
  # Incrementa contador
  i <- i + 1
}

#Identificador de los proyectos sobresalientes
print(proyectos_sobresalientes)

# Detalle de estos proyectos
detalle_sobresalientes <- proyectoInovacion %>% 
  filter(id_proyecto %in% proyectos_sobresalientes)

head(detalle_sobresalientes)
```

#Parte VII
```{r}

#Función 1: Calcular índice de eficiencia del proyecto

# función que calcula la eficiencia para cada proyecto
fn_calculo_eficiencia <- function(pub, pat, pres) {
  return((pub + pat) / pres)
}

# Usamos mutate junto con lapply
# lapply devuelve una lista, por eso usamos unlist() para 
# que se convierta en una columna (vector) de nuestro dataframe.
proyectoInovacion <- proyectoInovacion %>%
  mutate(
    eficiencia_proyecto = unlist(lapply(1:n(), function(i) {
      fn_calculo_eficiencia(publicaciones[i], patentes[i], presupuesto_usd[i])
    }))
  )

# Mostramos las 3 variables y el id del proyecto mas la eficiencia calculada del proyecto
proyectoInovacion %>% 
  select(id_proyecto, publicaciones, patentes, presupuesto_usd, eficiencia_proyecto) %>% 
  head(10)


#Función 2: Identificar proyectos con alto impacto

# Recibe un dataframe y devuelve solo IDs y Categoría de los proyectos de Alto Impacto
identificar_proyectos_impacto <- function(df) {
  
  # ac solo los de alto impacto
  df_filtrado <- df %>%
    filter(impacto == "Alto") %>%
    #solo id_proyecto y la categoria del proyecto
    select(id_proyecto, categoria_proyecto)
  
  return(df_filtrado)
}

# le pasamos el df 
resultado_alto_impacto <- lapply(list(proyectoInovacion), identificar_proyectos_impacto)

# extraemos el df que tiene la lista
df_alto_impacto_final <- resultado_alto_impacto[[1]]

# vemos los proyectos con alto impacto
print("Listado de Proyectos de Alto Impacto:")
print(df_alto_impacto_final)


# Función 3: Generar resumen estadístico 
# Recibe un dataframe y el nombre de la columna para analizar
generar_resumen_estadistico <- function(df, columna) {
  datos <- df[[columna]]
  
  resumen <- list(
    variable = columna,
    media = mean(datos),
    mediana = median(datos),
    desviacion_estandar = sd(datos),
    percentiles = quantile(datos, probs = c(0.25, 0.5, 0.75, 0.9))
  )
  return(resumen)
}

# Resumen estadístico del presupuesto 
resumen_de_variable <- lapply(list(proyectoInovacion), function(df) {
  generar_resumen_estadistico(df, "presupuesto_usd")
})

df_resumen_de_variable <- resumen_de_variable[[1]]

print("Resumen Estadístico de la variable:")
print(df_resumen_de_variable)



```



#Parte VIII
```{r}
#Grafica de barras para presupuesto de proyectos
ggplot(proyectoInovacion, aes(x = presupuesto_usd)) + geom_histogram( bins = 25, color = "white")

#Grafica de dispercion que muestra la relacion entre presupuesto y publicaciones por pais
grafica = ggplot(proyectoInovacion, aes(x = presupuesto_usd, y = publicaciones, color=pais,
size=publicaciones)) + geom_point() + scale_x_log10() + scale_y_log10()

ggplotly(grafica)

#Comparacion de prespuesto por area de tecnologia.
ggplot(proyectoInovacion, aes(x = area_tecnologica, y = presupuesto_usd)) + geom_boxplot() + ggtitle("Distribución del presupuesto por área tecnológica") 


```
#Parte IX
```{r}

#¿Qué áreas tecnológicas reciben mayor financiamiento?
#Con base de la grafica que relaciona preupuesto por area de tecnologia (boxplot) podemos observar que el area de agrotecnologia es quien tiene una inversion mayor respecto a los demás, seguido por Ciberseguridad y Biotecnologia. Podemos observar que tiene valores dispersos de presupuesto en funcion del país en donde son ejecutados, a pesar que todos estan expresados en una misma moneda (USD) para los diferentes paises

mayor_financiamiento<-proyectoInovacion %>%
  group_by(area_tecnologica) %>%
  summarize(financiamiento= sum(presupuesto_usd)) %>%
  arrange(desc(financiamiento))

mayor_financiamiento

#area_tecnologica    presupuesto resultados
#Agrotecnologia	    68127471	1.216954e-05		
#Ciberseguridad	    67395860	1.433972e-05		
#Biotecnologia	      62584589	1.244508e-05		
#Salud Digital	      60987706	9.845448e-06		
#Inteligencia Artificial	51087439	1.287092e-05		
#Nanotecnologia	    46277278	1.594650e-05		
#Energia Renovable	  38058983	1.810391e-05	

#¿Existe relación entre presupuesto y resultados?

paises_productividad<- proyectoInovacion %>%
  group_by(pais) %>%
  summarize(presupuesto=sum(presupuesto_usd), total_publicaciones = sum(publicaciones)) %>%
  arrange(desc(presupuesto)) 

paises_productividad

#Viendo la tabla, no existe una relación lineal de presupuestos con resultados, porque se puede visualizar que presupuestos grandes tiene menos publicaciones que paises con menos presupuesto en algunos casos, ejemplo Chile tiene un presupuesto mayor a Guatemala, sin embargo, la produccion de Chile respecto a publicaciones es menor a la cantidad de publicaciones realizadas en Guatemala. Dicho en otra forma en algunos paises si se tiene una relacion del presupuesto y sus resultados, pero en algunos paises no se tiene la misma productividad inclusive con presupuestos elevados. Ejemplo Colombia es el #7 en presupuesto pero es el #3 en mayor cantidad de publicaciones.

#pais      presupuesto total_publicaciones

#Bolivia	  43906712	229		
#Chile	    38547742	156		
#Guatemala	36342676	198		
#Panama	    36181954	213		
#Costa Rica	35260397	176		
#Ecuador	  33768193	154		
#Colombia	  32469578	207		
#Paraguay	  29745081	132		
#Argentina	27925922	163		
#Peru	      27685733	139	

#¿Qué países presentan mayor productividad?

#Tomando en consideracion que la productividad se mide por la operacion publicaciones / investigadores, podemos decir que Mexico es el pais con mayor productividad por cada investigador, sin embargo no se puede alcanzar que por lo menos la relacion sea 1 - 1, 1 publicacion por investigador.

paises_productividad<- proyectoInovacion %>%
  group_by(pais) %>%
  summarize(total_investigadores=sum(investigadores), total_publicaciones = sum(publicaciones)) %>%
  arrange(desc((total_investigadores / total_publicaciones))) 

paises_productividad

#paises con mayor productividad ordenas de mayor a menor
#pais        total_investigadores total_publicaciones
#Mexico	      427		              147		
#Paraguay	    374		              132		
#Chile	      425		              156		
#Guatemala	  532		              198		
#Uruguay	    287		              112		
#Panama	      541		              213		
#Peru	        352		              139		
#Colombia	    484		              207		
#Costa Rica	  409	              	176		
#Ecuador	    356	                154	


#¿Se identifican proyectos atípicos?
proyectos_atipicos<- proyectoInovacion %>%
  group_by(area_tecnologica) %>%
  summarize(presupuesto=mean(presupuesto_usd), 
            resultados=mean(indice_resultados),
            eficiencia= mean(eficiencia_proyecto)
            ) %>%
  arrange(desc(presupuesto))

proyectos_atipicos

#Se podria decir que los proyectos atipicos serian Energia renovable porque no es como los demas de a menos dinero, menos resultado, si no que es muy eficiente.
#Y también Salud digital porque tiene el presupuesto mas alto pero su resultado es muy bajo a comparación de los que si tienen presupuesto alto
#area_tecnologica          presupuesto   resultados    eficiencia 
#Salud Digital	            1108867.4	    9.845448e-06	8.550196e-06	
#Agrotecnologia	          1064491.7	    1.216954e-05	1.025525e-05	
#Biotecnologia	            1060755.7	    1.244508e-05	1.116466e-05	
#Nanotecnologia	          964110.0	    1.594650e-05	1.439794e-05	
#Ciberseguridad	          949237.5	    1.433972e-05	1.218313e-05	
#Inteligencia Artificial	  880817.9	    1.287092e-05	1.155476e-05	
#Energia Renovable	        845755.2	    1.810391e-05	1.620743e-05

proyectoInovacion




```

